import nodemailer from "nodemailer";

interface SendTimesheetEmailOptions {
  to: string;
  name: string;
  weekEnding: string;
  csvBuffer: Buffer;
  xlsxBuffer: Buffer;
}

function kebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export async function sendTimesheetEmail({
  to,
  name,
  weekEnding,
  csvBuffer,
  xlsxBuffer,
}: SendTimesheetEmailOptions): Promise<void> {
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || "587", 10),
    secure: process.env.SMTP_PORT === "465",
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  const kebabName = kebabCase(name);
  const subject = `NAS Timesheet - ${name} - Week Ending ${weekEnding}`;
  const filenameBase = `timesheet-${kebabName}-${weekEnding}`;

  await transporter.sendMail({
    from: process.env.SMTP_FROM,
    to,
    subject,
    html: `
      <h2>NAS Timesheet</h2>
      <p>Hi ${name},</p>
      <p>Please find your timesheet for the week ending <strong>${weekEnding}</strong> attached.</p>
      <p>Please review the attached files before forwarding to payroll at <a href="mailto:ambulance.payroll@hse.ie">ambulance.payroll@hse.ie</a>.</p>
      <p><strong>Reminder:</strong> Paysheets must be received no later than 12 noon each Monday.</p>
      <br>
      <p><em>Generated by NAS Timesheet Automation</em></p>
    `,
    attachments: [
      {
        filename: `${filenameBase}.csv`,
        content: csvBuffer,
        contentType: "text/csv",
      },
      {
        filename: `${filenameBase}.xlsx`,
        content: xlsxBuffer,
        contentType:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      },
    ],
  });
}
