export const NAS_STATIONS = [
  "Athlone",
  "Ballina",
  "Ballinasloe",
  "Bantry",
  "Birr",
  "Carlow",
  "Cashel",
  "Castlebar",
  "Cavan",
  "Clonmel",
  "Cork",
  "Donegal Town",
  "Drogheda",
  "Dublin - Loughlinstown",
  "Dublin - Swords",
  "Dublin - Tallaght",
  "Dublin - Townsend St",
  "Dundalk",
  "Dunmore East",
  "Ennis",
  "Enniscorthy",
  "Galway",
  "Gorey",
  "Kilkenny",
  "Killarney",
  "Letterkenny",
  "Limerick",
  "Longford",
  "Mallow",
  "Monaghan",
  "Mullingar",
  "Navan",
  "Nenagh",
  "New Ross",
  "Portlaoise",
  "Roscommon",
  "Sligo",
  "Thurles",
  "Tipperary",
  "Tralee",
  "Tuam",
  "Tullamore",
  "Waterford - City",
  "Waterford - Dungarvan",
  "Wexford",
] as const;

export type NASStation = (typeof NAS_STATIONS)[number];
