export const NAS_STATIONS = [
  "Carlow - Carlow Town",
  "Cavan - Cavan Town",
  "Cavan - Virginia",
  "Clare - Clare RRV",
  "Clare - Ennis",
  "Clare - Ennistymon",
  "Clare - Kilrush",
  "Clare - Scariff",
  "Cork - Bantry",
  "Cork - Bantry RRV",
  "Cork - Castletownbere",
  "Cork - Clonakility",
  "Cork - Cork City",
  "Cork - Fermoy",
  "Cork - Kanturk/Millstreet",
  "Cork - Macroom",
  "Cork - Mallow",
  "Cork - Mallow RRV",
  "Cork - Midleton/Youghal",
  "Cork - Skibbereen",
  "Donegal - Ballyshannon",
  "Donegal - Cardonagh",
  "Donegal - Donegal Town",
  "Donegal - Dungloe",
  "Donegal - Finn Valley",
  "Donegal - Killybegs",
  "Donegal - Letterkenny",
  "Donegal - Lifford",
  "Dublin - Cherry Orchard - Motorcycle Unit",
  "Dublin - Davitt Road",
  "Dublin - Loughlinstown",
  "Dublin - St. James's",
  "Dublin - Swords",
  "Dublin - Tallaght",
  "Galway - Ballinasloe",
  "Galway - Carraroe",
  "Galway - Clifden",
  "Galway - Galway City",
  "Galway - Loughrea",
  "Galway - Merlin Park",
  "Galway - Recess",
  "Galway - Tuam",
  "Kerry - Caherciveen",
  "Kerry - Dingle",
  "Kerry - Kenmare",
  "Kerry - Killarney",
  "Kerry - Listowel",
  "Kerry - Tralee",
  "Kildare - Athy",
  "Kildare - Maynooth",
  "Kildare - Naas",
  "Kilkenny - Kilkenny City",
  "Laois - Portlaoise",
  "Leitrim - Carrick on Shannon",
  "Leitrim - Manorhamilton",
  "Limerick - Limerick City",
  "Limerick - Newcastle West",
  "Longford - Longford Town",
  "Louth - Ardee",
  "Louth - Ardee RRV",
  "Louth - Drogheda",
  "Louth - Dundalk",
  "Mayo - Ballina",
  "Mayo - Belmullet",
  "Mayo - Castlebar",
  "Meath - Dunshauglin",
  "Meath - Navan",
  "Meath - Trim RVC",
  "Monaghan - Castleblayney",
  "Monaghan - Monaghan Town",
  "Offaly - Birr",
  "Offaly - Edenderry",
  "Offaly - Tullamore",
  "Offaly - Tullamore RRV",
  "Roscommon - Boyle",
  "Roscommon - Loughglynn",
  "Roscommon - Roscommon Town",
  "Roscommon - Roscommon RRV",
  "Sligo - Sligo Town",
  "Tipperary - Cashel",
  "Tipperary - Clonmel",
  "Tipperary - Nenagh",
  "Tipperary - Roscrea",
  "Tipperary - Thurles",
  "Tipperary - Tipperary RRV",
  "Tipperary - Tipperary Town",
  "Waterford - Dungarvan",
  "Waterford - Waterford City",
  "Westmeath - Athlone",
  "Westmeath - Mullingar",
  "Wexford - Enniscorthy",
  "Wexford - Gorey",
  "Wexford - New Ross",
  "Wexford - Wexford Town",
  "Wicklow - Arklow",
  "Wicklow - Baltinglass",
  "Wicklow - Wicklow Town",
  "Wicklow - Wicklow RRV",
] as const;

export type NASStation = (typeof NAS_STATIONS)[number];
